// =============================================================================
// AXI5-Stream Master VIP — Global Defines
// Single source of truth for every structural width and capability constant.
//
// Changing a macro here propagates to: seq_item field widths, interface signal
// widths, the agent_config virtual-handle type, and the tb_top interface
// instance — but ONLY because agent_config.sv and tb_top.sv carry explicit
// #(.DATA_W(`AXI_DATA_W), ...) bindings. Remove those bindings and this file
// stops being a source of truth.
//
// Generated by uvc_generator from verif_plan_axi_stream_master_v17_0.yaml
// =============================================================================
`ifndef AXI_STREAM_MASTER_VIP_DEFINES
`define AXI_STREAM_MASTER_VIP_DEFINES

// ── Structural widths (Spec Section 2.1 Signal list, Page 16) ────────────────
`define AXI_DATA_W            32
`define AXI_STRB_W            4          // AXI_DATA_W/8 — width of TKEEP and TSTRB
`define AXI_ID_W              8
`define AXI_DEST_W            4
`define AXI_USER_W            4

// ── Capability flags ────────────────────────────────────────────────────────
`define AXI_HAS_PAR           1          // AXI5 parity protection (Section 5.3, Page 46)
`define AXI_HAS_WAKE          1          // TWAKEUP present     (Section 2.3, Page 20)

// ── Timing and bounds ───────────────────────────────────────────────────────
`define CLK_PERIOD_PS         10
`define TREADY_WATCHDOG_MAX   100000     // Deadlock guard  (REQ_MST_01 / TC_MST_003)
`define MAX_PACKET_BEATS      256        // Packet bound    (REQ_MST_07)
`define TREADY_STALL_MAX      100        // Stall bound     (REQ_MST_02)

`endif
