// =============================================================================
// AXI5-Stream Slave VIP — Global Defines
// Single source of truth for every structural width and capability constant.
// Verification Role: SLAVE (Receiver). DUT: MASTER (Transmitter).
//
// Generated by uvc_generator from verif_plan_axi_stream_slave_v1_1.yaml
// =============================================================================
`ifndef AXI_STREAM_SLAVE_VIP_DEFINES
`define AXI_STREAM_SLAVE_VIP_DEFINES

// ── Structural widths (Spec Section 2.1 Signal list, Page 16) ────────────────
`define AXI_DATA_W            32
`define AXI_STRB_W            4          // AXI_DATA_W/8 — width of TKEEP and TSTRB
`define AXI_ID_W              8
`define AXI_DEST_W            4
`define AXI_USER_W            4

// ── Capability flags ────────────────────────────────────────────────────────
`define AXI_HAS_PAR           1          // AXI5 parity protection (Section 5.3, Page 46)
`define AXI_HAS_WAKE          1          // TWAKEUP present     (Section 2.3, Page 20)

// ── Timing and bounds ───────────────────────────────────────────────────────
`define CLK_PERIOD_PS         10
// The SLAVE waits for the DUT's TVALID, so its deadlock guard counts cycles
// awaiting TVALID (not TREADY as in the master VIP).
`define TVALID_WATCHDOG_MAX   100000     // Deadlock guard  (REQ_SLV_15 / watchdog)
`define MAX_PACKET_BEATS      256        // Packet bound    (REQ_SLV_07)
`define TREADY_STALL_MAX      100        // Back-pressure bound (REQ_SLV_02)

`endif
